#!/bin/sh

# Set these paths appropriately

BIN="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/bin"
CMD="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/cmd"
LIB="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
