#!/bin/sh

# Set these paths appropriately

BIN="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/bin"
CMD="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/cmd"
LIB="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
