#!/bin/sh

# Set these paths appropriately

BIN="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/bin"
CMD="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/cmd"
LIB="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/lithuanian-abbreviations
PARFILE=${LIB}/lithuanian.par
MWLFILE=${LIB}/lithuanian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
