#!/bin/sh

# Set these paths appropriately

BIN="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/bin"
CMD="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/cmd"
LIB="/home/maya/Downloads/heideltime-standalone-2.2.1/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

